---
title: "Data Collection Glassdoor"
author: "Grady Keene"
date: "10/2/2022"
output: html_document
---


```{r, include = FALSE}
library(rvest)
library(dplyr)
library(tidyverse)
library(lubridate)
library(repurrrsive)
library(ggimage)
library(grid)
library(ggrepel)
library(stopwords)
library(tm)
```

# Apple Engineer Positions (1-star)

```{r, include = FALSE}
## Apple Page 1
Apple_Link1 <- "https://www.glassdoor.com/Reviews/Apple-Engineering-Reviews-EI_IE1138.0,5_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Apple_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AP1)

## Apple Page 2
Apple_Link2 <- "https://www.glassdoor.com/Reviews/Apple-Engineering-Reviews-EI_IE1138.0,5_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Apple_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AP2)

## Apple Page 3
Apple_Link3 <- "https://www.glassdoor.com/Reviews/Apple-Engineering-Reviews-EI_IE1138.0,5_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Apple_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AP3)

## Apple Page 4
Apple_Link4 <- "https://www.glassdoor.com/Reviews/Apple-Engineering-Reviews-EI_IE1138.0,5_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Apple_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AP4)

## Apple Page 5
Apple_Link5 <- "https://www.glassdoor.com/Reviews/Apple-Engineering-Reviews-EI_IE1138.0,5_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Apple_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AP5)
```


```{r}
Apple_Engineer_Bad_Reviews <- rbind(AP1, AP2, AP3, AP4, AP5)

Apple_Engineer_Bad_Reviews %>%
  mutate(Company = "Apple") %>%
  select(Company, everything()) -> Apple_Engineer_Bad_Reviews
```


# Google Engineer Positions (1-star)

```{r, include=FALSE}
## Google Page 1

Google_Link1 <- "https://www.glassdoor.com/Reviews/Google-Engineering-Reviews-EI_IE9079.0,6_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Google_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
GP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(GP1)

## Google Page 2
Google_Link2 <- "https://www.glassdoor.com/Reviews/Google-Engineering-Reviews-EI_IE9079.0,6_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Google_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
GP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(GP2)

## Google Page 3
Google_Link3 <- "https://www.glassdoor.com/Reviews/Google-Engineering-Reviews-EI_IE9079.0,6_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Google_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
GP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(GP3)

## Google Page 4
Google_Link4 <- "https://www.glassdoor.com/Reviews/Google-Engineering-Reviews-EI_IE9079.0,6_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Google_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
GP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(GP4)

## Google Page 5
Google_Link5 <- "https://www.glassdoor.com/Reviews/Google-Engineering-Reviews-EI_IE9079.0,6_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Google_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
GP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(GP5)

```


```{r}

Google_Engineer_Bad_Reviews <- rbind(GP1, GP2, GP3, GP4, GP5)

Google_Engineer_Bad_Reviews %>%
  mutate(Company = "Google") %>%
  select(Company, everything()) -> Google_Engineer_Bad_Reviews
```


# Microsoft Engineer Positions (1-star)

```{r,include=FALSE}
## Microsoft Page 1

Microsoft_Link1 <- "https://www.glassdoor.com/Reviews/Microsoft-Engineering-Reviews-EI_IE1651.0,9_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Microsoft_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
MP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(MP1)

## Microsoft Page 2
Microsoft_Link2 <- "https://www.glassdoor.com/Reviews/Microsoft-Engineering-Reviews-EI_IE1651.0,9_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Microsoft_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
MP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(MP2)

## Microsoft Page 3
Microsoft_Link3 <- "https://www.glassdoor.com/Reviews/Microsoft-Engineering-Reviews-EI_IE1651.0,9_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Microsoft_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
MP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(MP3)


## Microsoft Page 4
Microsoft_Link4 <- "https://www.glassdoor.com/Reviews/Microsoft-Engineering-Reviews-EI_IE1651.0,9_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Microsoft_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
MP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(MP4)

## Microsoft Page 5
Microsoft_Link5 <- "https://www.glassdoor.com/Reviews/Microsoft-Engineering-Reviews-EI_IE1651.0,9_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Microsoft_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
MP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(MP5)

```


```{r}
Microsoft_Engineer_Bad_Reviews <- rbind(MP1, MP2, MP3, MP4, MP5)
Microsoft_Engineer_Bad_Reviews %>%
  mutate(Company = "Microsoft") %>%
  select(Company, everything()) -> Microsoft_Engineer_Bad_Reviews
```




# Meta Engineer Positions (1-star)

```{r,include=FALSE}
## Meta Page 1

Meta_Link1 <- "https://www.glassdoor.com/Reviews/Meta-Engineering-Reviews-EI_IE40772.0,4_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Meta_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
FP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(FP1)

## Meta Page 2
Meta_Link2 <- "https://www.glassdoor.com/Reviews/Meta-Engineering-Reviews-EI_IE40772.0,4_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Meta_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
FP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(FP2)

## Meta page 3
Meta_Link3 <- "https://www.glassdoor.com/Reviews/Meta-Engineering-Reviews-EI_IE40772.0,4_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Meta_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
FP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(FP3)

## Meta Page 4
Meta_Link4 <- "https://www.glassdoor.com/Reviews/Meta-Engineering-Reviews-EI_IE40772.0,4_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Meta_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
FP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(FP4)

## Meta Page 5
Meta_Link5 <- "https://www.glassdoor.com/Reviews/Meta-Engineering-Reviews-EI_IE40772.0,4_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Meta_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
FP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(FP5)

```


```{r}
Meta_Engineer_Bad_Reviews <- rbind(FP1, FP2, FP3, FP4, FP5)

Meta_Engineer_Bad_Reviews %>%
  mutate(Company = "Meta") %>%
  select(Company, everything()) -> Meta_Engineer_Bad_Reviews
```


# Uber Engineer Positions (1-star)

```{r,include=FALSE}
## Uber Page 1

Uber_Link1 <- "https://www.glassdoor.com/Reviews/Uber-Engineering-Reviews-EI_IE575263.0,4_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Uber_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
UP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(UP1)

## Uber Page 2
Uber_Link2 <- "https://www.glassdoor.com/Reviews/Uber-Engineering-Reviews-EI_IE575263.0,4_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Uber_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
UP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(UP2)

## Uber page 3
Uber_Link3 <- "https://www.glassdoor.com/Reviews/Uber-Engineering-Reviews-EI_IE575263.0,4_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Uber_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
UP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(UP3)

## Uber Page 4
Uber_Link4 <- "https://www.glassdoor.com/Reviews/Uber-Engineering-Reviews-EI_IE575263.0,4_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Uber_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
UP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(UP4)

## Uber Page 5
Uber_Link5 <- "https://www.glassdoor.com/Reviews/Uber-Engineering-Reviews-EI_IE575263.0,4_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Uber_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
UP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(UP5)

```


```{r}
Uber_Engineer_Bad_Reviews <- rbind(UP1, UP2, UP3, UP4, UP5)
Uber_Engineer_Bad_Reviews %>%
  mutate(Company = "Uber") %>%
  select(Company, everything()) -> Uber_Engineer_Bad_Reviews
```


# Airbnb Engineer Positions (1-star)

```{r,include=FALSE}
## Airbnb Page 1

Airbnb_Link1 <- "https://www.glassdoor.com/Reviews/Airbnb-Engineering-Reviews-EI_IE391850.0,6_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Airbnb_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
ArP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(ArP1)

## Airbnb Page 2
Airbnb_Link2 <- "https://www.glassdoor.com/Reviews/Airbnb-Engineering-Reviews-EI_IE391850.0,6_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Airbnb_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
ArP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(ArP2)

## Airbnb page 3
Airbnb_Link3 <- "https://www.glassdoor.com/Reviews/Airbnb-Engineering-Reviews-EI_IE391850.0,6_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Airbnb_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
ArP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(ArP3)

## Airbnb Page 4
Airbnb_Link4 <- "https://www.glassdoor.com/Reviews/Airbnb-Engineering-Reviews-EI_IE391850.0,6_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Airbnb_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
ArP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(ArP4)

## Airbnb Page 5
Airbnb_Link5 <- "https://www.glassdoor.com/Reviews/Airbnb-Engineering-Reviews-EI_IE391850.0,6_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Airbnb_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
ArP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(ArP5)

```


```{r}
Airbnb_Engineer_Bad_Reviews <- rbind(ArP1, ArP2, ArP3, ArP4, ArP5)
Airbnb_Engineer_Bad_Reviews %>%
  mutate(Company = "Airbnb") %>%
  select(Company, everything()) -> Airbnb_Engineer_Bad_Reviews
```


# Spotify Engineer Positions (1-star)

```{r,include=FALSE}
## Spotify Page 1

Spotify_Link1 <- "https://www.glassdoor.com/Reviews/Spotify-Engineering-Reviews-EI_IE408251.0,7_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Spotify_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
SP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(SP1)

## Spotify Page 2
Spotify_Link2 <- "https://www.glassdoor.com/Reviews/Spotify-Engineering-Reviews-EI_IE408251.0,7_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Spotify_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
SP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(SP2)

## Spotify page 3
Spotify_Link3 <- "https://www.glassdoor.com/Reviews/Spotify-Engineering-Reviews-EI_IE408251.0,7_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Spotify_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
SP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(SP3)

## Spotify Page 4
Spotify_Link4 <- "https://www.glassdoor.com/Reviews/Spotify-Engineering-Reviews-EI_IE408251.0,7_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Spotify_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
SP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(SP4)

## Spotify Page 5
Spotify_Link5 <- "https://www.glassdoor.com/Reviews/Spotify-Engineering-Reviews-EI_IE408251.0,7_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Spotify_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
SP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(SP5)

```


```{r}
Spotify_Engineer_Bad_Reviews <- rbind(SP1, SP2, SP3, SP4, SP5)
Spotify_Engineer_Bad_Reviews %>%
  mutate(Company = "Spotify") %>%
  select(Company, everything()) -> Spotify_Engineer_Bad_Reviews
```


# Twitter Engineer Positions (1-star)

```{r,include=FALSE}
## Twitter Page 1

Twitter_Link1 <- "https://www.glassdoor.com/Reviews/Twitter-Engineering-Reviews-EI_IE100569.0,7_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Twitter_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
TP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(TP1)

## Twitter Page 2
Twitter_Link2 <- "https://www.glassdoor.com/Reviews/Twitter-Engineering-Reviews-EI_IE100569.0,7_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Twitter_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
TP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(TP2)

## Twitter page 3
Twitter_Link3 <- "https://www.glassdoor.com/Reviews/Twitter-Engineering-Reviews-EI_IE100569.0,7_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Twitter_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
TP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(TP3)

## Twitter Page 4
Twitter_Link4 <- "https://www.glassdoor.com/Reviews/Twitter-Engineering-Reviews-EI_IE100569.0,7_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Twitter_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
TP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(TP4)

## Twitter Page 5
Twitter_Link5 <- "https://www.glassdoor.com/Reviews/Twitter-Engineering-Reviews-EI_IE100569.0,7_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Twitter_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
TP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(TP5)

```


```{r}
Twitter_Engineer_Bad_Reviews <- rbind(TP1, TP2, TP3, TP4, TP5)
Twitter_Engineer_Bad_Reviews %>%
  mutate(Company = "Twitter") %>%
  select(Company, everything()) -> Twitter_Engineer_Bad_Reviews
```



# Amazon Web Services Engineer Positions (1-star)

```{r,include=FALSE}
## Aws Page 1

Aws_Link1 <- "https://www.glassdoor.com/Reviews/Amazon-Web-Services-Engineering-Reviews-EI_IE7470741.0,19_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Aws_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AWP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AWP1)

## Aws Page 2
Aws_Link2 <- "https://www.glassdoor.com/Reviews/Amazon-Web-Services-Engineering-Reviews-EI_IE7470741.0,19_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Aws_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AWP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AWP2)

## Aws page 3
Aws_Link3 <- "https://www.glassdoor.com/Reviews/Amazon-Web-Services-Engineering-Reviews-EI_IE7470741.0,19_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Aws_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AWP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AWP3)

## Aws Page 4
Aws_Link4 <- "https://www.glassdoor.com/Reviews/Amazon-Web-Services-Engineering-Reviews-EI_IE7470741.0,19_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Aws_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AWP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AWP4)

## Aws Page 5
Aws_Link5 <- "https://www.glassdoor.com/Reviews/Amazon-Web-Services-Engineering-Reviews-EI_IE7470741.0,19_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Aws_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
AWP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(AWP5)

```


```{r}
Aws_Engineer_Bad_Reviews <- rbind(AWP1, AWP2, AWP3, AWP4, AWP5)
Aws_Engineer_Bad_Reviews %>%
  mutate(Company = "Amazon Web Services (AWS)") %>%
  select(Company, everything()) -> Aws_Engineer_Bad_Reviews
```


# Netflix Engineer Positions (1-star)

```{r,include=FALSE}
## Netflix Page 1

Netflix_Link1 <- "https://www.glassdoor.com/Reviews/Netflix-Engineering-Reviews-EI_IE11891.0,7_DEPT1007.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page1 = read_html(Netflix_Link1)
Star = page1%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page1%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page1%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page1%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page1%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
NP1 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(NP1)

## Netflix Page 2
Netflix_Link2 <- "https://www.glassdoor.com/Reviews/Netflix-Engineering-Reviews-EI_IE11891.0,7_DEPT1007_IP2.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page2 = read_html(Netflix_Link2)
Star = page2%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page2%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page2%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page2%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page2%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
NP2 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(NP2)

## Netflix page 3
Netflix_Link3 <- "https://www.glassdoor.com/Reviews/Netflix-Engineering-Reviews-EI_IE11891.0,7_DEPT1007_IP3.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page3 = read_html(Netflix_Link3)
Star = page3%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page3%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page3%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page3%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page3%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
NP3 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(NP3)

## Netflix Page 4
Netflix_Link4 <- "https://www.glassdoor.com/Reviews/Netflix-Engineering-Reviews-EI_IE11891.0,7_DEPT1007_IP4.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page4 = read_html(Netflix_Link4)
Star = page4%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page4%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page4%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page4%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page4%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
NP4 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(NP4)

## Netflix Page 5
Netflix_Link5 <- "https://www.glassdoor.com/Reviews/Netflix-Engineering-Reviews-EI_IE11891.0,7_DEPT1007_IP5.htm?sort.sortType=OR&sort.ascending=true&filter.iso3Language=eng&filter.employmentStatus=REGULAR&filter.employmentStatus=PART_TIME"
page5 = read_html(Netflix_Link5)
Star = page5%>% html_nodes("#ReviewsFeed .mr-xsm")%>%
  html_text()
Employee = page5%>% html_nodes(".eg4psks0")%>%
  html_text()
Review_Title = page5%>% html_nodes(".reviewLink")%>%
  html_text()
Date = page5%>% html_nodes(".middle.common__EiReviewDetailsStyle__newGrey")%>%
  html_text()
Pros = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth:nth-child(1) span")%>%
  html_text()
Cons = page5%>% html_nodes(".v2__EIReviewDetailsV2__fullWidth+ .v2__EIReviewDetailsV2__fullWidth span")%>%
  html_text()
NP5 = data.frame(Star, Employee, Review_Title, Date, Pros, Cons)
as_tibble(NP5)

```


```{r}
Netflix_Engineer_Bad_Reviews <- rbind(NP1, NP2, NP3, NP4, NP5)
Netflix_Engineer_Bad_Reviews %>%
  mutate(Company = "Netflix") %>%
  select(Company, everything()) -> Netflix_Engineer_Bad_Reviews
```



```{r}
Glassdoor_scraped <- rbind(Apple_Engineer_Bad_Reviews,Google_Engineer_Bad_Reviews,
                           Microsoft_Engineer_Bad_Reviews,Meta_Engineer_Bad_Reviews,
                           Uber_Engineer_Bad_Reviews, Airbnb_Engineer_Bad_Reviews,
                           Spotify_Engineer_Bad_Reviews, Twitter_Engineer_Bad_Reviews,
                           Aws_Engineer_Bad_Reviews, Netflix_Engineer_Bad_Reviews)
```

```{r}
Glassdoor_scraped %>%
  separate(Date, c("Review_Date", "Position_Title"), " - ") %>%
   mutate(C_F_Employee = ifelse(grepl("Current", Employee), "Current", "Former")) %>%
  select(Company, Position_Title, Review_Title, Cons, Pros, Review_Date, C_F_Employee) -> Glassdoor
```

```{r}
write.csv(Glassdoor,"Glassdoor.csv", row.names = FALSE)
```


```{r}
sapply(Glassdoor, class)
```



